import { Octokit } from "@octokit/rest";

const OWNER = process.env.GITHUB_OWNER ?? "";
const REPO = process.env.GITHUB_REPO ?? "";

if (!OWNER || !REPO) {
  console.error("[ERROR] GITHUB_OWNER or GITHUB_REPO env var is missing");
}

console.log(`[INFO] github-client loaded for ${OWNER}/${REPO}`);

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function withRateLimitRetry<T>(
  fn: () => Promise<T>,
  maxRetries: number = 3
): Promise<T> {
  let lastError: unknown;

  for (let attempt = 0; attempt < maxRetries; attempt++) {
    try {
      return await fn();
    } catch (err: unknown) {
      lastError = err;

      const isRateLimit =
        typeof err === "object" &&
        err !== null &&
        "status" in err &&
        (err as { status: number }).status === 403;

      if (isRateLimit) {
        const backoffMs = Math.pow(2, attempt) * 1000;
        console.warn(
          `[WARN] GitHub rate limit hit (attempt ${attempt + 1}/${maxRetries}). Waiting ${backoffMs}ms...`
        );
        await sleep(backoffMs);
      } else {
        throw err;
      }
    }
  }

  throw lastError;
}

async function getMainSha(octokit: Octokit): Promise<string> {
  const { data } = await withRateLimitRetry(() =>
    octokit.rest.git.getRef({
      owner: OWNER,
      repo: REPO,
      ref: "heads/main",
    })
  );
  return data.object.sha;
}

async function createBranch(
  octokit: Octokit,
  branchName: string,
  sha: string
): Promise<void> {
  await withRateLimitRetry(() =>
    octokit.rest.git.createRef({
      owner: OWNER,
      repo: REPO,
      ref: `refs/heads/${branchName}`,
      sha,
    })
  );
  console.log(`[INFO] Branch created: ${branchName}`);
}

async function commitPlaceholder(
  octokit: Octokit,
  branchName: string,
  suggestion: string,
  timestamp: string
): Promise<void> {
  const content = Buffer.from(
    `# Auto-Fix Suggestion\n\nGenerated: ${timestamp}\n\n## Claude Suggestion\n\n${suggestion}\n`
  ).toString("base64");

  await withRateLimitRetry(() =>
    octokit.rest.repos.createOrUpdateFileContents({
      owner: OWNER,
      repo: REPO,
      path: `fixes/suggestion-${timestamp}.md`,
      message: `fix: auto-suggestion ${timestamp}`,
      content,
      branch: branchName,
    })
  );
  console.log(`[INFO] Placeholder commit pushed to ${branchName}`);
}

export async function createFixPR(
  suggestion: string,
  errorType: string
): Promise<string> {
  const token = process.env.GITHUB_PAT ?? "";

  if (!token) {
    throw new Error("[ERROR] GITHUB_PAT secret is missing — cannot create PR");
  }

  const octokit = new Octokit({ auth: token });
  const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
  const branchName = `fix/auto-${timestamp}`;

  const mainSha = await getMainSha(octokit);
  await createBranch(octokit, branchName, mainSha);
  await commitPlaceholder(octokit, branchName, suggestion, timestamp);

  const pr = await withRateLimitRetry(() =>
    octokit.rest.pulls.create({
      owner: OWNER,
      repo: REPO,
      title: `[Auto-Fix] ${errorType} — ${timestamp}`,
      body: `## Auto-generated fix suggestion\n\n**Error type:** ${errorType}\n\n**Claude suggestion:**\n\n> ${suggestion}\n\n---\n_Generated by OpenClaw Coordinator. Review and merge if correct._`,
      head: branchName,
      base: "main",
    })
  );

  console.log(`[SUCCESS] PR created: ${pr.data.html_url}`);
  return pr.data.html_url;
}
